---
services:
  - anti_ddos:
      service_type: antiddos
      expected_suffix: /v1/{project_id}
  - auto_scale:
      service_type: as
      expected_suffix: /v1/{project_id}
  - block_storage:
      service_type: volume
      expected_suffix: /v3/{project_id}
  - cce:
      service_type: ccev2.0
      expected_suffix: /api/v3/projects/{project_id}
  - cloud_eye:
      service_type: ces
      expected_suffix: /V1.0/{project_id}
  - cloud_trace:
      service_type: cts
      expected_suffix: /v2.0/{project_id}
  - cloud_search:
      service_type: css
      expected_suffix: /V1.0/{project_id}
  - compute:
      service_type: compute
      expected_suffix: /v2.1/{project_id}
  - direct_connect:
      service_type: dcaas
      expected_suffix: /v2.0/dcaas/
  - distributed_cache:
      service_type: dcs
      expected_suffix: /v1.0/{project_id}
  - document_database:
      service_type: ddsv3
      expected_suffix: /v3/{project_id}
  - dedicated_host:
      service_type: deh
      expected_suffix: /v1.0/{project_id}
  - data_ingest:
      service_type: disv2
      expected_suffix: /v2/{project_id}
  - distributed_message:
      service_type: dms
      expected_suffix: /v1.0/{project_id}
  - dns:
      service_type: dns
      expected_suffix: /v2
  - data_warehouse:
      service_type: dwsv1
      expected_suffix: /v1.0/{project_id}
  - elb:
      service_type: network
      expected_suffix: /v2.0/
  - identity:
      service_type: identity
      expected_suffix: /v3
  - image:
      service_type: image
      expected_suffix: /v2
  - key_management:
      service_type: kms
      expected_suffix: /v1.0/{project_id}
  - log_tank:
      service_type: lts
      expected_suffix: /v2.0/{project_id}
  - map_reduce:
      service_type: mrs
      expected_suffix: /v2/{project_id}
  - nat_gateway:
      service_type: nat
      expected_suffix: /v2.0
  - network:
      service_type: network
      expected_suffix: /v2.0
  - orchestration:
      service_type: orchestration
      expected_suffix: /v1/{project_id}
  - private_link:
      service_type: plas
      expected_suffix: /v1.0/plasconnector
  - relational_database:
      service_type: rdsv3
      expected_suffix: /v3/{project_id}
  - storage_disaster_recovery:
      service_type: sdrs
      expected_suffix: /v1/{project_id}
  - scalable_filesystem:
      service_type: sharev2
      expected_suffix: /v2/{project_id}
  - scalable_filesystem_turbo:
      service_type: sfsturbo
      expected_suffix: /v1/{project_id}
  - simple_messaging:
      service_type: smnv2
      expected_suffix: /v2/{project_id}
  - software_repository:
      service_type: swr
      expected_suffix: /v2
  - tag_management:
      service_type: tms
      expected_suffix: /v1.0
  - vpc_endpoint:
      service_type: vpcep
      expected_suffix: /v1/{project_id}
  - web_firewall:
      service_type: waf
      expected_suffix: /v1/{project_id}


